In [1]:
import pandas as pd

In [114]:
total_year

,Unnamed: 0,제목,URL,조회수,업데이트 날짜,영상 길이,영상 좋아요 수,채널명,year,month,day
0,0,"보스이조후쿠오카에서 꼭 해야할 6가지, 뻔하지 않은 후쿠오카 여행하기",https://www.youtube.com/watch?v=02OZK_8FzOM,1444,2023-05-30,0:03:39,31.0,@Mingokim,2023,05,30
1,1,한국인 리뷰❌ ..? 샵사이다 하울 👗 | 가을 여행코디 🍁(사이즈 꿀팁 +프로모...,https://www.youtube.com/watch?v=Mx6TI5Q7tSw,5148,2023-08-30,0:11:09,79.0,@yekooooong,2023,08,30
2,2,-15kg 다이어트 레시피 ! 단호박 샌드위치 / 오트밀 팬케이크 / 쉽고 간단한 ...,https://www.youtube.com/watch?v=Jz4Xusw1DSE,2299,2023-08-25,0:12:22,71.0,@yekooooong,2023,08,25
3,3,VLOG 성공적인 제주 먹방 ✨(그만 먹어 제발) 제주여행 카페투어 / 메종글래드 ...,https://www.youtube.com/watch?v=AogRBhGjp2c,7152,2023-08-22,0:11:28,118.0,@yekooooong,2023,08,22
4,4,"VLOG 남자친구 공개..? 무한리필 흑돼지, 풍차해안도로🌊 , 인생사진 스팟 📸 ...",https://www.youtube.com/watch?v=3bx9eFTC3rw,6012,2023-08-16,0:07:20,90.0,@yekooooong,2023,08,16
...,...,...,...,...,...,...,...,...,...,...,...
9901,9901,(Sub) 고데기없이 하기 쉬운 4가지 헤어 스타일링💇🏼‍♀️ 까치머리•로우번•포인...,https://www.youtube.com/watch?v=oRvQ9MuodMI,120050,2022-09-24,0:14:57,NaN,희주,2022,09,24
9902,9902,(Sub) 동글동글 도토리상 가을 메이크업🌰 +인중과 중안부 짧게! 꿀팁 대방출,https://www.youtube.com/watch?v=ncWrW5QZRe4,237498,2022-09-17,0:17:41,NaN,희주,2022,09,17
9903,9903,"(Sub) Vlog👙 마지막 여름 즐기기, 고딩친구들과 양양, 제주 속 스페인, 미...",https://www.youtube.com/watch?v=kvtLSOfrT9w,89536,2022-09-05,1:01:03,NaN,희주,2022,09,5
9904,9904,(Sub) 나만 알고싶은.. 내 최애 데일리 악세사리 소개•하울💍✨ 디자이너 브랜드...,https://www.youtube.com/watch?v=mjLuICXDTBQ,103489,2022-08-20,0:18:56,NaN,희주,2022,08,20
9905,9905,"(Sub) 방콕 4일 브이로그🇹🇭 너무 핫한곳.., 인생숙소, 현지인 찐 맛집",https://www.youtube.com/watch?v=P2_7QA9ukWQ,225627,2022-08-13,0:43:20,NaN,희주,2022,08,13

In [7]:
# 영상 평균 term - 일년치 term을 평균내서 사용 ⇒ 성실도
# 영상 갯수 → 월 영상 갯수 ⇒ 성실도
total_year = pd.read_csv("Untitled_Folder/total_year_video_df.csv")
total_year.head()

,Unnamed: 0,제목,URL,조회수,업데이트 날짜,영상 길이,영상 좋아요 수,채널명
0,0,"보스이조후쿠오카에서 꼭 해야할 6가지, 뻔하지 않은 후쿠오카 여행하기",https://www.youtube.com/watch?v=02OZK_8FzOM,1444,2023-05-30,0:03:39,31.0,@Mingokim
1,1,한국인 리뷰❌ ..? 샵사이다 하울 👗 | 가을 여행코디 🍁(사이즈 꿀팁 +프로모...,https://www.youtube.com/watch?v=Mx6TI5Q7tSw,5148,2023-08-30,0:11:09,79.0,@yekooooong
2,2,-15kg 다이어트 레시피 ! 단호박 샌드위치 / 오트밀 팬케이크 / 쉽고 간단한 ...,https://www.youtube.com/watch?v=Jz4Xusw1DSE,2299,2023-08-25,0:12:22,71.0,@yekooooong
3,3,VLOG 성공적인 제주 먹방 ✨(그만 먹어 제발) 제주여행 카페투어 / 메종글래드 ...,https://www.youtube.com/watch?v=AogRBhGjp2c,7152,2023-08-22,0:11:28,118.0,@yekooooong
4,4,"VLOG 남자친구 공개..? 무한리필 흑돼지, 풍차해안도로🌊 , 인생사진 스팟 📸 ...",https://www.youtube.com/watch?v=3bx9eFTC3rw,6012,2023-08-16,0:07:20,90.0,@yekooooong

In [11]:
total_year['year'] = total_year['업데이트 날짜'].str[:4]
total_year['month'] = total_year['업데이트 날짜'].str[5:7]
total_year['day'] = total_year['업데이트 날짜'].str[8:]
total_year.head()

,Unnamed: 0,제목,URL,조회수,업데이트 날짜,영상 길이,영상 좋아요 수,채널명,year,month,day
0,0,"보스이조후쿠오카에서 꼭 해야할 6가지, 뻔하지 않은 후쿠오카 여행하기",https://www.youtube.com/watch?v=02OZK_8FzOM,1444,2023-05-30,0:03:39,31.0,@Mingokim,2023,05,30
1,1,한국인 리뷰❌ ..? 샵사이다 하울 👗 | 가을 여행코디 🍁(사이즈 꿀팁 +프로모...,https://www.youtube.com/watch?v=Mx6TI5Q7tSw,5148,2023-08-30,0:11:09,79.0,@yekooooong,2023,08,30
2,2,-15kg 다이어트 레시피 ! 단호박 샌드위치 / 오트밀 팬케이크 / 쉽고 간단한 ...,https://www.youtube.com/watch?v=Jz4Xusw1DSE,2299,2023-08-25,0:12:22,71.0,@yekooooong,2023,08,25
3,3,VLOG 성공적인 제주 먹방 ✨(그만 먹어 제발) 제주여행 카페투어 / 메종글래드 ...,https://www.youtube.com/watch?v=AogRBhGjp2c,7152,2023-08-22,0:11:28,118.0,@yekooooong,2023,08,22
4,4,"VLOG 남자친구 공개..? 무한리필 흑돼지, 풍차해안도로🌊 , 인생사진 스팟 📸 ...",https://www.youtube.com/watch?v=3bx9eFTC3rw,6012,2023-08-16,0:07:20,90.0,@yekooooong,2023,08,16

## 유튜버 월 별 영상개수

In [17]:
monthcount_df = total_year.groupby(['채널명','year','month']).count().reset_index()[['채널명','year','month','Unnamed: 0']]
monthcount_df.columns

Index(['채널명', 'year', 'month', 'Unnamed: 0'], dtype='object')

In [18]:
monthcount_df.columns = ['채널명', 'year', 'month', 'count']
monthcount_df.head()

           채널명  year month  count
0    @Mingokim  2023    05      1
1  @yekooooong  2022    08      3
2  @yekooooong  2022    09      1
3  @yekooooong  2023    01      2
4  @yekooooong  2023    02      3

In [19]:
monthcount_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2454 entries, 0 to 2453
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   채널명     2454 non-null   object
 1   year    2454 non-null   object
 2   month   2454 non-null   object
 3   count   2454 non-null   int64
dtypes: int64(1), object(3)
memory usage: 76.8+ KB

In [148]:
monthcount_df['날짜'] = monthcount_df['year'].astype(str) + '/' + monthcount_df['month'].astype(str)
monthcount_df

              채널명  year month  count       날짜
0       @Mingokim  2023    05      1  2023/05
1     @yekooooong  2022    08      3  2022/08
2     @yekooooong  2022    09      1  2022/09
3     @yekooooong  2023    01      2  2023/01
4     @yekooooong  2023    02      3  2023/02
...           ...   ...   ...    ...      ...
2449           희주  2023    04      3  2023/04
2450           희주  2023    05      3  2023/05
2451           희주  2023    06      4  2023/06
2452           희주  2023    07      4  2023/07
2453           희주  2023    08      2  2023/08

[2454 rows x 5 columns]

In [ ]:
mt = pd.read_excel('mater_table.xlsx', index_col=0)
mt

In [150]:
monthcount_df = monthcount_df.drop(['year','month'],axis = 1)
monthcount_df.columns

Index(['채널명', 'count', '날짜'], dtype='object')

In [163]:
monthcount_df.columns = ['유투버', '영상개수', '월']

In [170]:
mon_count = pd.merge(mt,monthcount_df,how = 'outer')

In [173]:
mon_count = mon_count.fillna(0)
mon_count.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3328 entries, 0 to 3327
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   유투버     3328 non-null   object
 1   월       3328 non-null   object
 2   영상개수    3328 non-null   float64
dtypes: float64(1), object(2)
memory usage: 104.0+ KB

In [174]:
mon_count.to_csv('mon_count.csv')