In [1]:
import os
import pandas as pd

c:\anaconda3\envs\py_397\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\anaconda3\envs\py_397\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
c:\anaconda3\envs\py_397\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [35]:
os.listdir(f'./data/labeled_data')

['labeling2.xlsx',
 '류스펜나_엑셀.xlsx',
 '몽몽_엑셀.xlsx',
 '민서_엑셀.xlsx',
 '안녕하새은 Saeeun_0_comment_data.csv',
 '안녕하새은 Saeeun_10_comment_data.csv',
 '안녕하새은 Saeeun_1_comment_data.csv',
 '안녕하새은 Saeeun_2_comment_data.csv',
 '안녕하새은 Saeeun_3_comment_data.csv',
 '안녕하새은 Saeeun_4_comment_data.csv',
 '안녕하새은 Saeeun_5_comment_data.csv',
 '안녕하새은 Saeeun_6_comment_data.csv',
 '안녕하새은 Saeeun_7_comment_data.csv',
 '안녕하새은 Saeeun_8_comment_data.csv',
 '안녕하새은 Saeeun_9_comment_data.csv',
 '윰_엑셀.xlsx',
 '재림_엑셀.xlsx']

In [97]:
label_comment_df = pd.DataFrame(columns=['comment', 'label'])

In [98]:
for file in os.listdir(f'./data/labeled_data')[5:16]:
    temp = pd.read_csv(f'./data/labeled_data/{file}', encoding='cp949')
    try:
        temp = temp[['comment', 'labeling']]
    except:
        temp = temp[['comment', 'labe;ing']]
    temp.columns = ['comment', 'label']
    label_comment_df = pd.concat([label_comment_df, temp], ignore_index=True)
label_comment_df

                                               comment label
0                                         언니 화장 너무 잘해용     1
1              언니 영상볼 때마다 옷 정보 궁금했는데 더보기란에 적어주셔서 감사해욤      1
2              당장 올리브영 가야해~~ 저도 금발이라 이번 메이크업 너무 좋아요>_<     1
3    진짜 제 모델이자 워너비 ㅠㅠ 사랑해요 언니 항상 언니같은 삶을 꿈만 꾸며 사네요 ...     1
4                   탈색 넘 고생인것 같아요ㅠㅠ 하지만 너무너무 잘어울리는 샌..     1
..                                                 ...   ...
566                                          Cute cute   NaN
567                                       헤어악세사리궁그매요ㅜㅜ   1.0
568                              안녕하새은 Saeeun님 아주예쁘군요.   1.0
569                                    웨이브헤어….눈뒤집어졋샌….   1.0
570                                                  1   NaN

[571 rows x 2 columns]

In [99]:
# label_comment_df에서 label이 0인건 지우고, -1인건 0으로 변환
label_comment_df = label_comment_df[label_comment_df['label'] != 0]
label_comment_df['label'] = label_comment_df['label'].apply(lambda x: 0 if x == -1 else x)

C:\Users\Mgyu\AppData\Local\Temp\ipykernel_26328\2753939130.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  label_comment_df['label'] = label_comment_df['label'].apply(lambda x: 0 if x == -1 else x)

In [100]:
temp = pd.read_csv(f'./data/labeled_data/labeling3.csv', encoding='cp949')
temp = temp[['comment', 'labeling']]
temp.columns = ['comment', 'label']
temp['label'] = temp['label'].apply(lambda x: 0 if x == -1 else x)
label_comment_df = pd.concat([label_comment_df, temp], ignore_index=True)
label_comment_df

                                               comment  label
0                                         언니 화장 너무 잘해용    1.0
1              언니 영상볼 때마다 옷 정보 궁금했는데 더보기란에 적어주셔서 감사해욤     1.0
2              당장 올리브영 가야해~~ 저도 금발이라 이번 메이크업 너무 좋아요>_<    1.0
3    진짜 제 모델이자 워너비 ㅠㅠ 사랑해요 언니 항상 언니같은 삶을 꿈만 꾸며 사네요 ...    1.0
4                   탈색 넘 고생인것 같아요ㅠㅠ 하지만 너무너무 잘어울리는 샌..    1.0
..                                                 ...    ...
951                                   오우 세 분 다 미모가 ㄷㄷㄷ    1.0
952                     15분대에 착용하고 계신 자켓 정보 알 수 있을까용?!    1.0
953                            비비안 목걸이 품번 알수있을까요? 넘예뻐요    1.0
954                              리본진주귀걸이..? 정보 너무 궁금해용    1.0
955                                 4:33 가디건 정보 궁금해요 ㅠ    1.0

[956 rows x 2 columns]

In [101]:
label_comment_df.value_counts('label')

label
1.0    906
0.0     14
Name: count, dtype: int64

In [102]:
temp = pd.read_excel(f'./data/labeled_data/labeling2.xlsx')
temp = temp[['comment', 'labeling']]
temp.columns = ['comment', 'label']
temp['label'] = temp['label'].apply(lambda x: 0 if x == -1 else x)
label_comment_df = pd.concat([label_comment_df, temp], ignore_index=True)
label_comment_df

                                                comment  label
0                                          언니 화장 너무 잘해용    1.0
1               언니 영상볼 때마다 옷 정보 궁금했는데 더보기란에 적어주셔서 감사해욤     1.0
2               당장 올리브영 가야해~~ 저도 금발이라 이번 메이크업 너무 좋아요>_<    1.0
3     진짜 제 모델이자 워너비 ㅠㅠ 사랑해요 언니 항상 언니같은 삶을 꿈만 꾸며 사네요 ...    1.0
4                    탈색 넘 고생인것 같아요ㅠㅠ 하지만 너무너무 잘어울리는 샌..    1.0
...                                                 ...    ...
2186  플루 고민만하고 아직 구매 안해봤는데 언니랑 피부타입이 너무 똑같아서 ..완전 뱀허...    1.0
2187  언니.. n년동안 등드름 가드름으로 오프숄더 한번 못입어봤어.. 등드름 흉터도 있어...    1.0
2188  플루 바디스크럽 저 진짜 애정템이에요!! 몇통을 비웠는지 모를정도로 제가 썼던 바디...    1.0
2189      앎쏭.. 어성초 기다리는 중에 선물 뭐야.... 아묻따 신청.... 고마워요...    1.0
2190  브라질라언 왁싱허는데 인그로운 쩌는데 \n스크럽 좋은제품을 못 찾앗어요 ㅠㅠ \n지...    1.0

[2191 rows x 2 columns]

In [103]:
label_comment_df.value_counts('label')

label
1.0    2123
0.0      23
Name: count, dtype: int64

In [104]:
for file in os.listdir(f'./data/labeled_data')[2:5] + os.listdir(f'./data/labeled_data')[-2:]:
    temp = pd.read_excel(f'./data/labeled_data/{file}')
    temp = temp[['comment', '긍부정']]
    temp['긍부정'] = temp['긍부정'].apply(lambda x: 0 if x == -1 else x)
    temp.columns = ['comment', 'label']
    label_comment_df = pd.concat([label_comment_df, temp], ignore_index=True)
    label_comment_df

In [105]:
label_comment_df

                                                 comment  label
0                                           언니 화장 너무 잘해용    1.0
1                언니 영상볼 때마다 옷 정보 궁금했는데 더보기란에 적어주셔서 감사해욤     1.0
2                당장 올리브영 가야해~~ 저도 금발이라 이번 메이크업 너무 좋아요>_<    1.0
3      진짜 제 모델이자 워너비 ㅠㅠ 사랑해요 언니 항상 언니같은 삶을 꿈만 꾸며 사네요 ...    1.0
4                     탈색 넘 고생인것 같아요ㅠㅠ 하지만 너무너무 잘어울리는 샌..    1.0
...                                                  ...    ...
15652                                                NaN    NaN
15653                                                NaN    NaN
15654                                                NaN    NaN
15655                                                NaN    NaN
15656                                                NaN    NaN

[15657 rows x 2 columns]

In [106]:
# label이 결측치인 행 제거
label_comment_df = label_comment_df.dropna(axis=0)
label_comment_df

                                                 comment  label
0                                           언니 화장 너무 잘해용    1.0
1                언니 영상볼 때마다 옷 정보 궁금했는데 더보기란에 적어주셔서 감사해욤     1.0
2                당장 올리브영 가야해~~ 저도 금발이라 이번 메이크업 너무 좋아요>_<    1.0
3      진짜 제 모델이자 워너비 ㅠㅠ 사랑해요 언니 항상 언니같은 삶을 꿈만 꾸며 사네요 ...    1.0
4                     탈색 넘 고생인것 같아요ㅠㅠ 하지만 너무너무 잘어울리는 샌..    1.0
...                                                  ...    ...
15524                                         지금도 그저 예쁨     1.0
15537  성형은 사실 .. 한다고 김태희만큼 이뻐지는거 아님 그냥 안하고 사는게 맞는거타요....    0.0
15541                                하는것도 나쁘지 않을것 같은데욥ㅋㅋ    0.0
15547                               재수술하면 지금보다 성형 더 티날 듯    0.0
15550  너무 팔랑귀세여… 본인이 평소에 불만이 없었는데 다른 사람 말만 듣고 성형하는건 좀...    0.0

[4858 rows x 2 columns]

In [107]:
# 중복 확인
label_comment_df.drop_duplicates(inplace=True)

# 인덱스 초기화
label_comment_df.reset_index(drop=True, inplace=True)
# 데이터 타입 변경
label_comment_df['label'] = label_comment_df['label'].astype(int)
label_comment_df

C:\Users\Mgyu\AppData\Local\Temp\ipykernel_26328\1679232162.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  label_comment_df.drop_duplicates(inplace=True)
C:\Users\Mgyu\AppData\Local\Temp\ipykernel_26328\1679232162.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  label_comment_df['label'] = label_comment_df['label'].astype(int)

                                                comment  label
0                                          언니 화장 너무 잘해용      1
1               언니 영상볼 때마다 옷 정보 궁금했는데 더보기란에 적어주셔서 감사해욤       1
2               당장 올리브영 가야해~~ 저도 금발이라 이번 메이크업 너무 좋아요>_<      1
3     진짜 제 모델이자 워너비 ㅠㅠ 사랑해요 언니 항상 언니같은 삶을 꿈만 꾸며 사네요 ...      1
4                    탈색 넘 고생인것 같아요ㅠㅠ 하지만 너무너무 잘어울리는 샌..      1
...                                                 ...    ...
4731                                         지금도 그저 예쁨       1
4732  성형은 사실 .. 한다고 김태희만큼 이뻐지는거 아님 그냥 안하고 사는게 맞는거타요....      0
4733                                하는것도 나쁘지 않을것 같은데욥ㅋㅋ      0
4734                               재수술하면 지금보다 성형 더 티날 듯      0
4735  너무 팔랑귀세여… 본인이 평소에 불만이 없었는데 다른 사람 말만 듣고 성형하는건 좀...      0

[4736 rows x 2 columns]

In [108]:
label_comment_df['label'].value_counts()

label
1    4564
0     172
Name: count, dtype: int64

In [110]:
label_comment_df.to_csv('./data/labeled_data/label_comment_df.csv', index=False)