In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

c:\anaconda3\envs\py_397\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\anaconda3\envs\py_397\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
c:\anaconda3\envs\py_397\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [43]:
df_comment = pd.read_csv('./data/total_comment_data.csv', index_col=0)
df_comment.dropna(inplace=True)
df_comment.head()

C:\Users\Mgyu\AppData\Local\Temp\ipykernel_9084\286740298.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_comment = pd.read_csv('./data/total_comment_data.csv', index_col=0)

,youtube_id,comment,like_num,comment_date,owner_channel,video_num
0,songheepark9809,다양한 체험들 알려주셔서 고마워요!! 영상에 나온 거 다 너무 재밌어보여요밍고님 영...,0.0,3개월 전,@Mingokim,0
1,moonsunkang6257,후쿠오카 가고싶다,0.0,3개월 전,@Mingokim,0
2,userck8uk7tu5q,10년전 후쿠오카에 갔었는데. \n이영상을 보니 또한번 가야겠어요. \n보이스도...,0.0,3개월 전,@Mingokim,0
3,bobslee6308,"밍고짱 넘 부럽당,,후쿠오카에 액티비티가 이렇게 많았구남,, 재밌었겠댜🫶",0.0,3개월 전,@Mingokim,0
4,heeeunbyun1238,후쿠오카 놀러가야지,0.0,3개월 전,@Mingokim,0

In [94]:
temp_total = pd.DataFrame(columns=df_comment.columns)
# for i in range(9):
#     temp = df_comment[(df_comment['owner_channel'] == '기우쌤') & (df_comment['video_num'] == i)]
#     print(len)
#     temp_total = pd.concat([temp_total, temp])
temp_total = df_comment[(df_comment['owner_channel'] == '기우쌤')]
print(temp_total['youtube_id'].nunique(), len(temp_total))
temp_total['youtube_id'].value_counts()

12741 15685

youtube_id
b0o0dlesn0o0dles    34
usergq4ri6gh4c      27
Sumj1qu             24
proverbs0315        20
kiudesign           19
                    ..
userbz5cq5js9x       1
poppiria9647         1
rachaelbower6435     1
userhc5gy9fn5k       1
userdj8hw8vi7s       1
Name: count, Length: 12741, dtype: int64

In [138]:
df_frame = pd.read_excel('./data/mater_table.xlsx')
df_frame

      Unnamed: 0        유투버        월
0              0  @Mingokim  2022/08
1              1  @Mingokim  2022/09
2              2  @Mingokim  2022/10
3              3  @Mingokim  2022/11
4              4  @Mingokim  2022/12
...          ...        ...      ...
3323        3323         희주  2023/04
3324        3324         희주  2023/05
3325        3325         희주  2023/06
3326        3326         희주  2023/07
3327        3327         희주  2023/08

[3328 rows x 3 columns]

In [131]:
total_year_video_df = pd.read_csv('./data/total_year_video_df.csv', index_col=0)
total_year_video_df

,제목,URL,조회수,업데이트 날짜,영상 길이,영상 좋아요 수,채널명
0,"보스이조후쿠오카에서 꼭 해야할 6가지, 뻔하지 않은 후쿠오카 여행하기",https://www.youtube.com/watch?v=02OZK_8FzOM,1444,2023-05-30,0:03:39,31.0,@Mingokim
1,한국인 리뷰❌ ..? 샵사이다 하울 👗 | 가을 여행코디 🍁(사이즈 꿀팁 +프로모...,https://www.youtube.com/watch?v=Mx6TI5Q7tSw,5148,2023-08-30,0:11:09,79.0,@yekooooong
2,-15kg 다이어트 레시피 ! 단호박 샌드위치 / 오트밀 팬케이크 / 쉽고 간단한 ...,https://www.youtube.com/watch?v=Jz4Xusw1DSE,2299,2023-08-25,0:12:22,71.0,@yekooooong
3,VLOG 성공적인 제주 먹방 ✨(그만 먹어 제발) 제주여행 카페투어 / 메종글래드 ...,https://www.youtube.com/watch?v=AogRBhGjp2c,7152,2023-08-22,0:11:28,118.0,@yekooooong
4,"VLOG 남자친구 공개..? 무한리필 흑돼지, 풍차해안도로🌊 , 인생사진 스팟 📸 ...",https://www.youtube.com/watch?v=3bx9eFTC3rw,6012,2023-08-16,0:07:20,90.0,@yekooooong
...,...,...,...,...,...,...,...
9901,(Sub) 고데기없이 하기 쉬운 4가지 헤어 스타일링💇🏼‍♀️ 까치머리•로우번•포인...,https://www.youtube.com/watch?v=oRvQ9MuodMI,120050,2022-09-24,0:14:57,NaN,희주
9902,(Sub) 동글동글 도토리상 가을 메이크업🌰 +인중과 중안부 짧게! 꿀팁 대방출,https://www.youtube.com/watch?v=ncWrW5QZRe4,237498,2022-09-17,0:17:41,NaN,희주
9903,"(Sub) Vlog👙 마지막 여름 즐기기, 고딩친구들과 양양, 제주 속 스페인, 미...",https://www.youtube.com/watch?v=kvtLSOfrT9w,89536,2022-09-05,1:01:03,NaN,희주
9904,(Sub) 나만 알고싶은.. 내 최애 데일리 악세사리 소개•하울💍✨ 디자이너 브랜드...,https://www.youtube.com/watch?v=mjLuICXDTBQ,103489,2022-08-20,0:18:56,NaN,희주
9905,"(Sub) 방콕 4일 브이로그🇹🇭 너무 핫한곳.., 인생숙소, 현지인 찐 맛집",https://www.youtube.com/watch?v=P2_7QA9ukWQ,225627,2022-08-13,0:43:20,NaN,희주

In [290]:
df_frame['충성시청자_비율'] = np.nan
df_frame['댓글 수'] = np.nan
df_frame['영상 수'] = np.nan
df_frame

      Unnamed: 0        유투버        월  충성시청자_비율  댓글 수  영상 수
0              0  @Mingokim  2022/08       NaN   NaN   NaN
1              1  @Mingokim  2022/09       NaN   NaN   NaN
2              2  @Mingokim  2022/10       NaN   NaN   NaN
3              3  @Mingokim  2022/11       NaN   NaN   NaN
4              4  @Mingokim  2022/12       NaN   NaN   NaN
...          ...        ...      ...       ...   ...   ...
3323        3323         희주  2023/04       NaN   NaN   NaN
3324        3324         희주  2023/05       NaN   NaN   NaN
3325        3325         희주  2023/06       NaN   NaN   NaN
3326        3326         희주  2023/07       NaN   NaN   NaN
3327        3327         희주  2023/08       NaN   NaN   NaN

[3328 rows x 6 columns]

In [264]:
num_list

Index([6, 7], dtype='int64')

In [261]:
df_comment.loc[df_comment['video_num'].str.len() > 3, 'video_num'] = df_comment.loc[df_comment['video_num'].str.len() > 3, 'video_num'].str.split('_').str[-1]

In [283]:
df_comment['video_num'] = df_comment['video_num'].astype(int)

In [270]:
total_year_video_df[total_year_video_df['채널명'] == '뽐니']

,제목,URL,조회수,업데이트 날짜,영상 길이,영상 좋아요 수,채널명
3982,(sub) 가을 미리보기🔍 세미스모키 부담스럽지 않은 한 끗 디테일은?! (뽐니픽 ...,https://www.youtube.com/watch?v=nOh6gmBKylc,28060,2023-08-25,0:21:06,508.0,뽐니
3983,(sub) 오랜만에 수다수다 GRWM・맑고 청초한 가을 데일리 메이크업🤎 (뉴 샵민...,https://www.youtube.com/watch?v=b6n46DqIkSY,27844,2023-08-23,0:21:36,451.0,뽐니
3984,"(sub) 현직 패션 브랜드 대표 가방엔 뭐가 있을까?👜 신박한 꿀팁, 꿀템 + 뽐...",https://www.youtube.com/watch?v=syDAHIOT1To,18574,2023-08-17,0:27:48,314.0,뽐니
3985,(sub) 요즘 최애템들로 해 본 실패없는 필승조합 메이크업🫡 (요즘 빠진 베이스템...,https://www.youtube.com/watch?v=RK1zljletYc,28454,2023-08-14,0:16:07,409.0,뽐니
3986,(sub) 요즘 찐템 꿀템 꽉꽉 채운 𝐖𝐡𝐚𝐭’𝐬 𝐢𝐧 𝐦𝐲 𝐛𝐚𝐠? 👜 (여름 필...,https://www.youtube.com/watch?v=hK3E0MZdGUI,56191,2023-08-12,0:25:36,884.0,뽐니
...,...,...,...,...,...,...,...
4079,"본식 한 달 남은 예비신부의 관리 모음.zip (얼굴형 관리, 다이어트, 화이트 태닝)",https://www.youtube.com/watch?v=wn2YHbH3E8M,27420,2022-08-19,0:29:08,333.0,뽐니
4080,(sub) ❤️‍🔥찐텐 주의❤️‍🔥 뷰튜버 7년차 드.디.어 블랙헤드 케어 정착템 ...,https://www.youtube.com/watch?v=r6_IL_dvI94,52880,2022-08-13,0:19:28,873.0,뽐니
4081,(sub) 꿀템 대잔치🍯 샵 30곳 넘게 다니면서 영업 당했던 아이템들로 해 본 샵...,https://www.youtube.com/watch?v=l3039ts53kA,62192,2022-08-12,0:28:33,998.0,뽐니
4082,(sub) 단종되면 본사 찾아갈 각🔥 나만 알기 아까운 숨은 히든템들 (선케어 맛집...,https://www.youtube.com/watch?v=pt8KqFKBL6o,35191,2022-08-06,0:21:31,592.0,뽐니
4083,(sub) 대전 동네샵에서 웨딩 헤메 받아 봤는데요..? 아니.. 너무 잘하는데?,https://www.youtube.com/watch?v=PCIttHeQNmw,39069,2022-08-03,0:17:38,654.0,뽐니

In [293]:
for name in total_year_video_df['채널명'].unique():
    print(list(total_year_video_df['채널명'].unique()).index(name), name)
    temp_total = total_year_video_df[total_year_video_df['채널명'] == name]
    temp_total.reset_index(drop=True, inplace=True)
    for date in df_frame['월'].unique():
        year, month = map(int, date.split('/'))
        num_list = temp_total[(temp_total['업데이트 날짜'].str.split('-').str[0].astype(int) == year) & (temp_total['업데이트 날짜'].str.split('-').str[1].astype(int) == month)].index
        temp_month = pd.DataFrame(columns=df_comment.columns)
        for i in num_list:
            temp = df_comment[(df_comment['owner_channel'] == name) & (df_comment['video_num'] == i)]
            temp_month = pd.concat([temp_month, temp])
        temp_frequency = pd.DataFrame(temp_month.groupby('youtube_id').count()['comment'])
        df_frame.loc[(df_frame['월'] == date) & (df_frame['유투버'] == name), '댓글 수'] = len(temp_month)
        df_frame.loc[(df_frame['월'] == date) & (df_frame['유투버'] == name), '영상 수'] = len(num_list)
        if len(temp_frequency) == 0:
            df_frame.loc[(df_frame['월'] == date) & (df_frame['유투버'] == name), '충성시청자_비율'] = np.nan
            
            
        else:
            df_frame.loc[(df_frame['월'] == date) & (df_frame['유투버'] == name), '충성시청자_비율'] = len(temp_frequency[temp_frequency['comment'] > 1]) / len(temp_frequency)

            #print(len(temp_frequency[temp_frequency['comment'] > 1]) / len(temp_frequency))

0 @Mingokim
1 @yekooooong
2 benny8282_nail
3 bird 정은
4 Coco Riley
5 COLIZET콜리젯TV
6 Coral코랄
7 DAISY 데이지
8 DrDr
9 Hazel하정
10 hello,jiyoung안녕하신지영
11 HYEBBEUM혜쁨
12 Jaelimize재림
13 jang.hope장호프
14 jella젤라
15 JJUDRE쭈드레
16 jjuE쭈이
17 Junsoo함준수
18 juyeomi
19 KINGSTON킹스턴
20 Kongsueni콩슈니
21 krystal수정
22 Laila라일라
23 lamuqe
24 lasagesse지혜
25 LUCY루씨
26 moodin은송
27 Ood 오드
28 Ori오리의소비로그
29 Queen Solmee
30 SELFCARE 결
31 So Young
32 SOLA솔아
33 SOONSIKI
34 SSUIMAG
35 SUMINI
36 Summer-mute썸뮤
37 Syong'sbeauty숑스뷰티
38 tency텐씨
39 VIVA여나
40 wandashow
41 wonhee
42 yootrue_in_air
43 zoopeach 지우
44 강성
45 거노건호geonoGH
46 고태용
47 궁달언니
48 그레인Grain
49 극찐ZZINI
50 기우쌤
51 김남령
52 김다혜
53 김선우 SUN WOO
54 김송정머리터 복구매직 복구펌 원조
55 김습습
56 김지유JIYUKIM
57 꽃세히sayblossom
58 나나nana
59 네일그랜마nailgranma
60 느린양반
61 다다뷰티
62 다예
63 다현쌤
64 담쓰뷰티DamsBeauty
65 댄서 리안의 JOB다한 일상
66 더네일리영thenaily_young
67 디렉터 파이
68 디얼빈dearbeen
69 디자이너윤뉴
70 라웁스laoops
71 라이크스윗망고-HealthyandSimpleLife
72 랏뚜Beauty
73 러브솔
74 럭히히봉heebong
75 런던혜원
76 레삐디오(RepitProfessional)
77 로로와아델라roroadella
78 로맨틱민서MINSEO
79 로즈픽스
80 로즈하
81 로지Rosie
82 루루팡
83 루이연 ruiyeon
84 루치나
85 루혜LUHYE
86 류스펜나
87 리음lieum
88 마이구미Gumhee
89 맨지
90 메리지히_MerryJihee
91 메멘토설은
92 몽몽이는 몽몽
93 몽키TV
94 묘빵뷰티
95 묭실언니 허슬기
96 무지개빅깔
97 문군MOONGOON
98 미니월드
99 미닝Minning
100 미대살롱
101 미소제인
102 미욤miyom
103 미팩TV미라클스토리
104 민제이MINJ
105 밍몽드
106 바이도하
107 박돌핀Bakdollphin
108 배령BELL
109 보고싶진아
110 보니bonny
111 보은 boeun
112 뷰티마스터윤지연TVbeautymasterYOON
113 뷰티엔젤
114 뷰티트레이너쭈언니
115 뷰티펄진주PEARL
116 뷰티홈즈
117 브이록
118 비타1000서영
119 뽐니
120 상아튜브
121 상은언니
122 상자의 신발상자
123 새얀
124 샨토끼
125 서달로그
126 서진온니SJonly
127 세나킴의건강&뷰티
128 센트위키Season1
129 셴나Shenna's
130 소리쌤
131 소연뷰티
132 소의튜브
133 송아현
134 송이송이
135 송필드
136 수리Suri
137 수박온니
138 수성헤어
139 수수하SOSOHA
140 수앤유Sooandyou
141 숩니subni
142 스라테티션 slathetician
143 스완SWAN_현실남자뷰티
144 스튜디오앤드-StudioA.N.D
145 심플리 수빈
146 썸블리
147 씬님
148 씬스타일ssinstyle
149 아두찌로그
150 아름송이
151 아름하다
152 아옳이
153 아이엠맹
154 안녕설기
155 안녕영경
156 안녕하새은
157 애슐리Ashley
158 엄마의 보물창고
159 에센스룸
160 에이프롬
161 엘리
162 엘피디
163 여음IsYeoeum
164 연두콩
165 연선yeonsun
166 예리네일yerinails
167 예순이
168 예스럽다
169 예영이예영
170 오늘의하늘
171 오자Oza
172 옥뷰티
173 온리원서의
174 올니드
175 와디의 신발장
176 욘조yonzo
177 우린
178 웨이채널
179 유나YUNA
180 유네영
181 유리숍
182 유아델리urdaily
183 유이레컬러OneandOnly
184 유자차Ujatea
185 윤민쌤
186 윤새 yoonsae
187 윤이니yooniny
188 윤이든
189 윤터터yunteoteo
190 율럽
191 윰YUM
192 은조미
193 이니아니
194 인애킴
195 잉구EEN9
196 장쌀롱
197 정다윤
198 정어리jungeory
199 정우Jungwoo
200 정채
201 제시하다Jessiehada
202 제이시JAYCEE
203 제타zetta
204 조니로그
205 조돌월드JodolWorld
206 쥬쥬쥬세요
207 쥴리쿠
208 지안씨
209 지애
210 지옹이
211 지인언니
212 진아쌤
213 집 팔아 화장품 사는 깡나
214 짱세zzangse
215 찬살롱TV남자머리해결사
216 채니 CHAENY
217 채르니Chaerny
218 채소
219 최은경의 관리사무소
220 최칸나KANNA
221 춤추는선진이
222 치유
223 코코초이
224 큐도리
225 파우더룸
226 팔색쪼마리
227 패션 팬아시아
228 패션-정찬양
229 팽대표의퍼스널
230 포푼젤
231 퓨딩
232 프롬핸fromhaen
233 프리윤freeyoon
234 피로
235 피알남 피부과전문의 김홍석
236 핑글PINKJJELLY
237 핑피박_의료미용과겸임교수
238 하나네집
239 하능is
240 하롱롱
241 하비언니
242 하빠happa
243 해딩HAEDING
244 현실언니
245 혜봉
246 호수
247 홍대미향언니
248 홍띠끄hongtique
249 화장품비평가최지현
250 화장품읽어주는남자화읽남
251 회사원A
252 효진조
253 후니세탁소HUNILAUNDRY
254 후메이크업whozmakeup
255 희주

In [295]:
df_frame = df_frame.iloc[:, 1:]
df_frame

            유투버        월  충성시청자_비율   댓글 수  영상 수
0     @Mingokim  2022/08       NaN    0.0   0.0
1     @Mingokim  2022/09       NaN    0.0   0.0
2     @Mingokim  2022/10       NaN    0.0   0.0
3     @Mingokim  2022/11       NaN    0.0   0.0
4     @Mingokim  2022/12       NaN    0.0   0.0
...         ...      ...       ...    ...   ...
3323         희주  2023/04  0.196078  125.0   3.0
3324         희주  2023/05  0.158076  362.0   3.0
3325         희주  2023/06  0.190789  201.0   4.0
3326         희주  2023/07  0.116456  474.0   4.0
3327         희주  2023/08  0.144000  147.0   2.0

[3328 rows x 5 columns]

In [296]:
df_frame.to_csv('./data/충성도.csv', encoding='utf-8-sig', index=False)